// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/animations/CardFlip.tsx": () => import("../components/mockups/animations/CardFlip.tsx"),
  "./components/mockups/animations/CounterStats.tsx": () => import("../components/mockups/animations/CounterStats.tsx"),
  "./components/mockups/animations/EmberParticles.tsx": () => import("../components/mockups/animations/EmberParticles.tsx"),
  "./components/mockups/animations/GlitchText.tsx": () => import("../components/mockups/animations/GlitchText.tsx")
};
